services:
  backend:
    build:
      context: ./backend
    command: [ uvicorn, app.main:app, --reload, --host=0.0.0.0 ]
    user: root
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
